### ISSUE TITLE
CentOS 7 no longer supports MD5 certs

### ISSUE THREAD

**Issue by nerijus** [lkeijser/stonevpn#7]
As you can see in https://www.centos.org/forums/viewtopic.php?f=50&t=47210 md5 support has been removed as it's no longer regarded as secure (even by Microsoft).
The certs generated by stonevpn can no longer be used to connect to the openvpn server on CentOS 7.x (6.x is OK).

It works if I modify /etc/systemd/system/openvpn@.service file by adding:
[Service]
Environment="OPENSSL_ENABLE_MD5_VERIFY=1 NSS_HASH_ALG_SUPPORT=+MD5"

I see there is digest="md5" in a few places in /lib/python2.7/site-packages/StoneVPN/app.py. What can I use instead of "md5" here?

**Comment by lkeijser** [comment]
Hi, you can use 'sha1' instead. I've fixed it and will push an update soon (also RPM for EPEL).

**Comment by nerijus** [comment]
Could you please make a github release too? Now the latest is 0.4.15, but the latest Fedora package is 0.4.16.

**Comment by nerijus** [comment]
Also could you please commit your changes to github repository, o paste the diff here?

**Comment by lkeijser** [comment]
I've just pushed all changes

**Comment by nerijus** [comment]
I've just tested it, the certificates now are accepted by the openvpn server on CentOS 7.x, thanks!
