### ISSUE TITLE
Support for inline certificates in OpenVPN configuration files

### ISSUE THREAD

**Issue by t4nec0** [lkeijser/stonevpn#8]
Hi,
don't know if because of the latest Android versions (tested with 7 and 8), or because of new OpenVPN client versions for Android, I had problems importing the configuration files and the certificates with Android OpenVPN client. There was no way to let the app find the related certificate files.

I was able to manually hack the configuration file and embed all the certificates **in** the configuration file itself, by using a syntax  like <ca> .... </ca>.

Refs:

- https://github.com/schwabe/ics-openvpn
- https://www.brainfart.sg/index.php/2012/05/embedding-certificate-into-openvpn-config/
- https://community.openvpn.net/openvpn/wiki/IOSinline

It would be great if StoneVPN could manage that syntax as well.

**Comment by lkeijser** [comment]
I'm pretty sure that's already an option:

```
[root@vpn ~]# stonevpn -f t4nec0 -n t4nec0 -o android 
Creating t4nec0.key and t4nec0.crt for t4nec0
Certificate is valid for 365 day(s).
Generating Android configuration file
[root@testvpn ~]# cat /var/stonevpn/test-t4nec0.ovpn 
daemon
dev tun
remote 1.2.3.4
port 1194
client
tls-client
comp-lzo
ping 15
ping-restart 45
ping-timer-rem
persist-tun
persist-key
verb 7
proto tcp
cipher AES-256-CBC

<ca>
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
</ca>

<cert>
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
</cert>

<key>
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
</key>
```
I use this myself in combination with the latest OpenVPN Connect client, as well as another android app called simply "OpenVPN for Android" and it works like you want. I'm using Android 8.0.0 btw

**Comment by t4nec0** [comment]
OK, thanks, I'm sure the version I've installed (0.4.12 AFAIK) hasn't that option. I will try and upgrade to the latest.

**Comment by lkeijser** [comment]
Okay, looks like android support was added in version 0.4.15, so yeah, 0.4.12 didn't have that yet. Let me know if upgrading solves the issue for you.
